@startuml
skinparam sequenceArrowThickness 4
skinparam roundcorner 20
autonumber

Пользователь -> Устройство: Голосовая команда или вопрос
Устройство -> Яндекс.Диалоги: Отправить аудио
Яндекс.Диалоги -> Яндекс.Диалоги: ASR (распознать речь в текст)
Яндекс.Диалоги -> Ассистент: Запрос в webhook обработчика навыка
Ассистент -> Ассистент: Парсинг запроса

alt если нужна авторизация
    Ассистент -> Авторизация: Запрос на авторизацию (логин, пароль)
    Авторизация -> Авторизация: Проверка пользователя
    Авторизация -> Авторизация: Генерация JWT tokens
    Авторизация --> Ассистент: JWT tokens (Access, Refresh)
end

Ассистент -> Ассистент: Подготовка запроса для сервиса

alt поиск фильма
    Ассистент -> "Сервис поиска": Запрос поиска фильма
    "Сервис поиска" --> Ассистент
else рекомендация
    Ассистент -> "Рекомендательная система": Запрос рекомендации
    "Рекомендательная система" --> Ассистент
else уведомление
    Ассистент -> "Система уведомлений": Запрос на отправку уведомления
    "Система уведомлений" --> Ассистент
end


Ассистент -> Ассистент: Парсинг ответа
Ассистент -> Ассистент: Подготовка ответа
Ассистент --> Яндекс.Диалоги: Вернуть ответ
Яндекс.Диалоги -> Яндекс.Диалоги: TTS (преобразование текста в речь)
Яндекс.Диалоги --> Устройство: Вернуть аудио
Устройство --> Пользователь: Произнести ответ

@enduml